version: '3'

# This docker-compose is for developer convenience, not for running in production.

services:

  spark-master:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7077:7077"
      - "8080:8080"
    environment:
      - MODE=master
      - PORT=7077
      - WEBPORT=8080

  spark-worker1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - spark-master
    environment:
      - MODE=worker
      - PORT=8091
      - WEBPORT=8081
      - CORES=2
      - MEM=1G
      - SPARK_MASTER_URL=spark://spark-master:7077

  spark-worker2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - spark-master
    environment:
      - MODE=worker
      - PORT=8092
      - WEBPORT=8082
      - CORES=2
      - MEM=1G
      - SPARK_MASTER_URL=spark://spark-master:7077

  notebook:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4040:4040"
      - "4041:4041"
    depends_on:
      - spark-master
    environment:
      - MODE=notebook
      - PORT=4041
      - SPARK_MASTER_URL=spark://spark-master:7077